-- INSERT INTO users ( name, surname, join_date) VALUES ( 'Bartek', 'Czosnyka',  '2020-01-22');
-- INSERT INTO user_credentials ( login, password, email, role, is_password_changed, users_id) VALUES ('Bartek', 'password1',  'bartek@gmail.com', 'ADMIN', 'TRUE', 1);
--
